<?php

namespace CarnetAdresses\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

use CarnetAdresses\UserBundle\Entity\User;


/**
 * AddressBookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressBookRepository extends EntityRepository {
    
    /**
     * Récupère tous les User qui sont dans les contacts de l'User spécifié par
     * son 'username'.
     * 
     * @param string username
     * @return array of User
     */
    public function findAddressBookOf(User $user) {
        $builder = $this->createQueryBuilder('ab');
        $builder->where('ab.owner = :owner')
                ->setParameter('owner', $user);
        
       return $builder->getQuery()->getOneOrNullResult();
    }
}
