<?php

namespace CarnetAdresses\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AddressBookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressBookRepository extends EntityRepository {
    
    /**
     * Récupère tous les User qui sont dans les contacts de l'User spécifié par
     * son 'username'.
     * 
     * @param string username
     * @return array of User
     */
    public function findAllContactsOf($username) {
        $builder = $this->createQueryBuilder('ab.contacts');
        $builder->join('ab.owner', 'owner')
                ->addSelect('owner')
                ->where('owner.username = :username')
                ->setParameter('username', $username);
        
       return $builder->getQuery()->getResult();
    }
}
